SUPABASE_URL = "https://dywpgwkpwqmszflmpetc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5d3Bnd2twd3Ftc3pmbG1wZXRjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTYwMDIxMywiZXhwIjoyMDY1MTc2MjEzfQ.GIrfl2PDrw4NBdSvmQEhsnxTEv7Bzc2kLotaWhc0Ils"
OPENAI_API_KEY = "your_openai_key"